#INSERT INTO `quotingdojo`.`quotes`
#(`quote`,`name`,`date`) VALUES ('I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion.','Alexander the Great','1970-01-01 00:00:01');
#INSERT INTO `quotingdojo`.`quotes`
#(`quote`,`name`,`date`) VALUES ('I make lame jokes','Trey','2014-02-01 12:00:00');
#INSERT INTO `quotingdojo`.`quotes`
#(`quote`,`name`,`date`) VALUES('To struggle is to learn.','Michael Choi','2013-01-18 12:00:00');
#INSERT INTO `quotingdojo`.`quotes`
#(`quote`,`name`,`date`) VALUES('Trey, your code is broken','India Meisner','2012-01-01 12:00:00');
#SELECT * FROM `quotingdojo`.`quotes`;
-- MySQL Script generated by MySQL Workbench
-- Tue Dec  8 12:09:41 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `created_at_UNIQUE` (`created_at` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
